### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by srikharshashi** [softshapeorg/diana-mobile#14]
Guys I have like 400 issues when I try to set up the environment in my PC.
Lots of Gradle Build Errors.Changed the SDK version and everything.

**Comment by HasanAlqaisi** [comment]
Hi

If you followed the instructions in CONTRIBUTING.md and got those errors too.

I think that is because this project hasn't migrated to null safety yet.

So downgrade the project to a version less than null safety version maybe will help.

Or another option is to upgrade the packages to null safety but should avoid the conflict problems as well.

I will check it out ASAP

**Comment by HasanAlqaisi** [comment]
It was because of the json_serializable version is null safe and the project wasn't migrated yet, and this thing caused the errors you've been through.

I didn't want to downgrade the packages to be non-null safe so I migrated the project to null safety and everything is fine!
